tiptree_project/accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from .views import CustomPasswordResetView,CustomPasswordResetDoneView,CustomPasswordResetConfirmView,CustomPasswordResetCompleteView

app_name = 'accounts'

urlpatterns = [
    path('regist', views.regist, name = 'regist'),
    path('confirm', views.confirm, name = 'confirm'),
    path('login', views.login_view, name = 'login'),
    path('logout', views.logout_view, name = 'logout'),
    path('password_reset', CustomPasswordResetView.as_view(), name='password_reset'), 
    path('password_reset/done', CustomPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', CustomPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', CustomPasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('my_page', views.my_page, name = 'my_page'),
    path('user_edit', views.user_edit, name = 'user_edit'),
    path('change_password', views.change_password, name = 'change_password'),
]

tiptree_project/home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('home', views.home, name = 'home'),
]

tiptree_project/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('create_post', views.create_post, name = 'create_post'),
    path('confirm', views.confirm, name = 'confirm'),
    path('edit_post/<int:post_id>', views.edit_post, name = 'edit_post'),
    path("<int:post_id>/save/", views.toggle_save, name="toggle_save"),
    path('saved', views.saved_post_list, name = 'saved_post_list'),
    path("<int:post_id>/help/", views.toggle_help, name="toggle_help"),
    path('helped', views.helped_post_list, name = 'helped_post_list'),
    path("<int:post_id>/", views.post_detail, name="post_detail"),
    path("<int:post_id>/comment/", views.comment_create, name="comment_create"),
    path("<int:post_id>/supplement/", views.supplement_create, name="supplement_create"),
    path("<int:post_id>/delete/", views.post_delete, name="post_delete"),
    path("supplement/<int:supplement_id>/supplement_reply/",views.supplement_reply,name="supplement_reply"),
    path("comment/<int:comment_id>/comment_reply/",views.comment_reply,name="comment_reply"),
    path("supplement/<int:supplement_id>/delete/",views.supplement_delete,name="supplement_delete"),
    path("supplement_reply/<int:supplement_reply_id>/delete/",views.supplement_reply_delete,name="supplement_reply_delete"),
    path("comment/<int:comment_id>/delete/",views.comment_delete,name="comment_delete"),
    path("comment_reply/<int:comment_reply_id>/delete/",views.comment_reply_delete,name="comment_reply_delete"),
]

tiptree_project/tiptree_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.portfolio, name='portfolio'),
    path('accounts/',include('accounts.urls')),
    path('home/',include('home.urls')),
    path('posts/',include(('posts.urls','posts'),namespace='posts')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

tiptree_project/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="utf-8">
        {% load static %}
        
        <!-- FontAwesome CDN -->
         <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
        <!--bootstrap-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{% static 'base.css' %}">
        {% block extra_css %}
        {% endblock %}
    </head>
    <body>
        <header>
            <div class="header-container">
                <a href="{% url 'home:home' %}" class="logo">TipTree</a>
                <nav class="menu">
                    {% if user.is_authenticated %}
                        <a href="{% url 'accounts:my_page' %}"><i class="far fa-user-circle"></i>マイページ</a>
                        <a href="{% url 'posts:create_post' %}"><i class="far fa-plus-square"></i>投稿</a>
                    {% else %}
                        <a href="{% url 'accounts:login' %}"><i class="far fa-user-circle"></i>マイページ</a>
                        <a href="{% url 'accounts:login' %}"><i class="far fa-plus-square"></i>投稿</a>
                    {% endif %}
                </nav>
            </div>
        </header>
        {% block content %}{% endblock %}
        {% block extra_js %}{% endblock %}
    </body>
</html>

tiptree_project/templates/portfolio.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <title>Portfolio</title>
</head>
<body>
    <div class="container">
        <h1>作品No.1 TipTree</h1>
        <p>TipTreeは、「見る楽しさ」「共有する喜び」「学び合う価値」がそろったライフハック共有プラットフォームです。</p>
        <p>気になる投稿は保存して後から確認でき、コメントや補足説明を通じて知識を深め合えます。</P>
        <p>また、カテゴリー別に検索できたり、人気な投稿のランキングが表示される仕組みにより、</p>
        <p>実用的な情報を見つけやすく、より便利な暮らしを提供します。</p>
    <div/>
    <button onclick="location.href='{% url 'accounts:login' %}'">
        このアプリにアクセス
    </button>
</body>
</html>