tiptree_project/home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('home', views.home, name = 'home'),
]

tiptree_project/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('create_post', views.create_post, name = 'create_post'),
    path('confirm', views.confirm, name = 'confirm'),
    path('edit_post/<int:post_id>', views.edit_post, name = 'edit_post'),
    path("<int:post_id>/save/", views.toggle_save, name="toggle_save"),
    path('saved', views.saved_post_list, name = 'saved_post_list'),
    path("<int:post_id>/help/", views.toggle_help, name="toggle_help"),
    path('helped', views.helped_post_list, name = 'helped_post_list'),
    path("<int:post_id>/", views.post_detail, name="post_detail"),
    path("<int:post_id>/comment/", views.comment_create, name="comment_create"),
    path("<int:post_id>/supplement/", views.supplement_create, name="supplement_create"),
    path("<int:post_id>/delete/", views.post_delete, name="post_delete"),
    path("supplement/<int:supplement_id>/supplement_reply/",views.supplement_reply,name="supplement_reply"),
    path("comment/<int:comment_id>/comment_reply/",views.comment_reply,name="comment_reply"),
    path("supplement/<int:supplement_id>/delete/",views.supplement_delete,name="supplement_delete"),
    path("supplement_reply/<int:supplement_reply_id>/delete/",views.supplement_reply_delete,name="supplement_reply_delete"),
    path("comment/<int:comment_id>/delete/",views.comment_delete,name="comment_delete"),
    path("comment_reply/<int:comment_reply_id>/delete/",views.comment_reply_delete,name="comment_reply_delete"),
]

tiptree_project/tiptree_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.portfolio, name='portfolio'),
    path('accounts/',include('accounts.urls')),
    path('home/',include('home.urls')),
    path('posts/',include(('posts.urls','posts'),namespace='posts')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

tiptree_project/posts/models.py
from django.db import models
from accounts.models import User
from django.core.validators import FileExtensionValidator
import tempfile
import subprocess
import json
from django.core.exceptions import ValidationError

class Category(models.Model):
    name = models.CharField(max_length=50)
    parent = models.ForeignKey(
        'self',
        on_delete = models.PROTECT,
        null = True,
        blank = True,
        related_name = 'subcategories'
    )
    
    def __str__(self):
        if self.parent:
            return f"{self.parent.name}:{self.name}"
        return self.name


def validate_video_duration(value):
    try:
        with tempfile.NamedTemporaryFile(delete=False, suffix='.mp4') as tmp:
            for chunk in value.chunks():
                tmp.write(chunk)
            tmp_path = tmp.name
            
        result = subprocess.run(
            [
                'ffprobe',
                '-v','error',
                '-show_entries','format=duration',
                '-of','json',
                tmp_path,
            ],
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True
        )
        
        info = json.loads(result.stdout or '{}')
        duration = float(info.get('format',{}).get('duration', 0))
        
        if duration == 0:
            raise ValidationError('動画を確認できませんでした。')
        
        if duration > 60:
            raise ValidationError('動画は1分以内にしてください。')
        
    except ValidationError:
        raise
    
    except Exception:
        raise ValidationError('動画を確認できませんでした。')
    

class Post(models.Model):
    title = models.CharField(max_length=100)
    category = models.ForeignKey(Category, on_delete=models.PROTECT)
    thumbnail = models.FileField(
        upload_to='posts/thumbnails/',
        validators=[FileExtensionValidator(['jpg','jpeg','png'],message="JPEGまたはPNG画像を選択してください")])
    video = models.FileField(
        upload_to='posts/videos/',
        validators=[FileExtensionValidator(['mp4','mov','avi'],message="MP4,MOV,AVIから動画を選択してください"),validate_video_duration])
    content = models.TextField()
    description = models.TextField(null=True, blank=True)
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    uppdated_at = models.DateTimeField(auto_now=True)
    saved_users = models.ManyToManyField(
        User,
        through="SavePost",
        related_name="saved_posts"
    )
    helped_users = models.ManyToManyField(
        User,
        through="HelpPost",
        related_name="helped_posts"
    )
    
    @property
    def help_count(self):
        return self.helped_by.count()
    
    @property
    def comment_count(self):
        return self.comments.count()
    
    class Meta:
        db_table = 'post'
        
        
class HelpPost(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='help_posts')
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='helped_by')
    created_at = models.DateTimeField(auto_now_add=True)
        
    class Meta:
        db_table = 'help_posts'
        unique_together = ('user','post')
        
        
class SavePost(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='save_posts')
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='saved_by')
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'save_posts'
        unique_together = ('user','post')
        
        
class Comments(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='sent_comments')
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    content = models.TextField()
    create_at = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        db_table = 'comments'
        
class CommentReply(models.Model):
    comment = models.ForeignKey(Comments, on_delete=models.CASCADE, related_name="comment_replies")
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    create_at = models.DateTimeField(auto_now_add=True)

        
class Supplements(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='sent_supplements')
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='supplements')
    content = models.TextField()
    create_at = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        db_table = 'supplements'
        
class SupplementReply(models.Model):
    supplement = models.ForeignKey(Supplements, on_delete=models.CASCADE, related_name="supplement_replies")
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    create_at = models.DateTimeField(auto_now_add=True)

tiptree_project/posts/views.py
from django.shortcuts import render,redirect,get_object_or_404
from . import forms
from .models import Post,SavePost,HelpPost,Supplements,Comments,CommentReply,SupplementReply
from django.contrib.auth.decorators import login_required
import os, uuid
from django.core.paginator import Paginator
from django.core.files.storage import default_storage
from django.core.files.base import ContentFile
from django.core.files import File
import logging
logger = logging.getLogger(__name__)


@login_required
def create_post(request):
    create_post_form = forms.CreatePostForm(request.POST or None, request.FILES or None)

    if create_post_form.is_valid():
        # モデルインスタンスを作る（DBには保存しない）
        post = create_post_form.save(commit=False)
        post.user = request.user

        # --- 一時保存処理（thumbnail と video を MEDIA_ROOT/tmp/ に保存） ---
        tmp_folder = 'tmp'
        thumb = create_post_form.cleaned_data.get('thumbnail')
        video = create_post_form.cleaned_data.get('video')

        temp_paths = {} #一時保存ファイルの管理表　削除、参照する際に用いる
        if thumb:
            ext = os.path.splitext(thumb.name)[1]
            tmp_name = f'{tmp_folder}/{uuid.uuid4().hex}{ext}'

            content = ContentFile(b'')
            for chunk in thumb.chunks():
                content.write(chunk)

            saved_path = default_storage.save(tmp_name, content)
            post.thumbnail.name = saved_path
            temp_paths['thumbnail'] = saved_path
            
            #ext=extension(拡張子),os.path.splitext:ファイル名を名前[0],拡張子[1]に分解する関数

        if video:
            ext = os.path.splitext(video.name)[1]
            tmp_name = f'{tmp_folder}/{uuid.uuid4().hex}{ext}'

            content = ContentFile(b'')
            for chunk in video.chunks():
                content.write(chunk)

            saved_path = default_storage.save(tmp_name, content)
            post.video.name = saved_path
            temp_paths['video'] = saved_path

        # 保存した一時パスをセッションに入れておく（confirmで参照 / backで削除に使える）
        request.session['temp_post_files'] = temp_paths

        return render(
            request,
            'posts/confirm.html',
            context={'create_post_form': create_post_form, 'post': post}
        )

    return render(
        request,
        'posts/create_post.html',
        context={'create_post_form': create_post_form}
    )
    

@login_required
def confirm(request):
    if request.method != "POST":
        return redirect('posts:create_post')

    create_post_form = forms.CreatePostForm(request.POST or None, request.FILES or None, validate_file=False)
    action = request.POST.get('action')

    temp_paths = request.session.get('temp_post_files', {})

    if action == 'back':
        # 戻るときは一時ファイルを削除してフォームに戻す
        for p in temp_paths.values():
            try:
                default_storage.delete(p)
            except Exception as e:
                logger.warning(f"Temp file delete failed: {p} ({e})")
        request.session.pop('temp_post_files', None)  #temp_post_filesがあれば削除
        return render(request, "posts/create_post.html", context={
            'create_post_form': create_post_form
        })

    elif action == 'done' and create_post_form.is_valid():
        post = create_post_form.save(commit=False)
        post.user = request.user

        for field_name, temp_path in temp_paths.items():

            if default_storage.exists(temp_path):
                with default_storage.open(temp_path, 'rb') as f:
                    file_data = File(f)
                    original_name = os.path.basename(temp_path)
                    ext = os.path.splitext(original_name)[1]

                    # UUID + 拡張子
                    new_filename = f"{uuid.uuid4().hex}{ext}"

                    getattr(post, field_name).save(
                        new_filename,
                        file_data,
                        save=False,
                    )
                post.save()

        # セッションの temp パスを消す
        request.session.pop('temp_post_files', None)
        return redirect('accounts:my_page')

    # それ以外（バリデーションNGなど）
    return render(request, "posts/confirm.html", context={
        'create_post_form': create_post_form
    })
    

@login_required
def edit_post(request, post_id):
    post = get_object_or_404(Post, post_id)
    edit_post_form = forms.EditPostForm(
        request.POST or None, request.FILES or None, instance=post
    )
    if edit_post_form.is_valid():
        edit_post_form.save()
        return redirect('accounts:my_page')
    
    return render(request,'posts/edit_post.html',context={
        'edit_post_form':edit_post_form
    })

@login_required
def toggle_save(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    user = request.user

    saved = SavePost.objects.filter(user=user, post=post)

    if saved.exists():
        saved.delete()
    else:
        SavePost.objects.create(user=user, post=post)

    return redirect(request.META.get("HTTP_REFERER", "/"))


@login_required
def saved_post_list(request):
    posts = Post.objects.filter(
        saved_users=request.user
    ).order_by('-saved_by__created_at')  # ← ここ重要！！

    paginator = Paginator(posts, 12)  # 1ページ12件
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    return render(request, 'posts/saved_post_list.html', {
        'page_obj': page_obj,
    })
    
    
@login_required
def toggle_help(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    user = request.user

    helped = HelpPost.objects.filter(user=user, post=post)

    if helped.exists():
        helped.delete()
    else:
        HelpPost.objects.create(user=user, post=post)

    return redirect(request.META.get("HTTP_REFERER", "/"))


@login_required
def helped_post_list(request):
    posts = Post.objects.filter(
        helped_users=request.user
    ).order_by('-helped_by__created_at')  # ← ここ重要！！

    paginator = Paginator(posts, 12)  # 1ページ12件
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    return render(request, 'posts/helped_post_list.html', {
        'page_obj': page_obj,
    })
    

def post_detail(request, post_id):
    post = get_object_or_404(Post, id=post_id)

    comments = post.comments.select_related('user').order_by('create_at')
    supplements = post.supplements.select_related('user').order_by('create_at')

    comment_form = forms.CommentForm()
    supplement_form = forms.SupplementForm()
    supplement_reply_form = forms.SupplementReplyForm()

    return render(request, 'posts/post_detail.html', {
        'post': post,
        'comments': comments,
        'supplements': supplements,
        'comment_form': comment_form,
        'supplement_form': supplement_form,
        'supplement_reply_form': supplement_reply_form,
    })
    
    
@login_required
def post_delete(request, post_id):
    post = get_object_or_404(Post, id=post_id, user=request.user)

    if request.method == "POST":
        post.delete()
        return redirect('posts:my_page') 


@login_required
def comment_create(request, post_id):
    post = get_object_or_404(Post, id=post_id)

    if request.method == 'POST':
        comment_form = forms.CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.post = post
            comment.user = request.user
            comment.save()

    return redirect('posts:post_detail', post_id=post.id)


@login_required
def comment_delete(request, comment_id):
    comment = get_object_or_404(Comments, id=comment_id, user=request.user)

    if request.method == "POST":
        comment.delete()
        return redirect(request.META.get("HTTP_REFERER", "/"))


@login_required
def comment_reply(request, comment_id):
    comment = get_object_or_404(Comments, id=comment_id)

    if request.method == 'POST':
        comment_reply_form = forms.CommentReplyForm(request.POST)
        if comment_reply_form.is_valid():
            comment_reply = comment_reply_form.save(commit=False)
            comment_reply.comment = comment
            comment_reply.user = request.user
            comment_reply.save()

    return redirect('posts:post_detail', post_id=comment.post.id)


@login_required
def comment_reply_delete(request, comment_reply_id):
    comment_reply = get_object_or_404(CommentReply, id=comment_reply_id, user=request.user)

    if request.method == "POST":
        comment_reply.delete()
        return redirect(request.META.get("HTTP_REFERER", "/"))


@login_required
def supplement_create(request, post_id):
    post = get_object_or_404(Post, id=post_id)

    if request.method == 'POST':
        supplement_form = forms.SupplementForm(request.POST)
        if supplement_form.is_valid():
            supplement = supplement_form.save(commit=False)
            supplement.post = post
            supplement.user = request.user
            supplement.save()

    return redirect('posts:post_detail', post_id=post.id)


@login_required
def supplement_delete(request, supplement_id):
    supplement = get_object_or_404(Supplements, id=supplement_id, user=request.user)

    if request.method == "POST":
        supplement.delete()
        return redirect(request.META.get("HTTP_REFERER", "/"))


@login_required
def supplement_reply(request, supplement_id):
    supplement = get_object_or_404(Supplements, id=supplement_id)

    if request.method == 'POST':
        supplement_reply_form = forms.SupplementReplyForm(request.POST)
        if supplement_reply_form.is_valid():
            supplement_reply = supplement_reply_form.save(commit=False)
            supplement_reply.supplement = supplement
            supplement_reply.user = request.user
            supplement_reply.save()

    return redirect('posts:post_detail', post_id=supplement.post.id)


@login_required
def supplement_reply_delete(request, supplement_reply_id):

tiptree_project/templates/posts/confirm.html
{% extends "base.html" %}
{% load static %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'posts/css/confirm.css' %}">
{% endblock %}

{% block content %}
    <form method="POST" action="{% url 'posts:confirm'%}">
        {% csrf_token %}
        <h2>この内容で投稿する場合は 投稿ボタン を押してください。</h2>
        <table>
            <tr><td>タイトル</td><td>{{create_post_form.title.value}}</td></tr>
            <tr><td>カテゴリー</td><td>{{create_post_form.category}}</td></tr>
<tr>
    <td>サムネイル画像</td>
    <td>
        {% if post.thumbnail %}
            <img src="{{ post.thumbnail.url }}" alt="{{ post.title }}のサムネイル">
        {% endif %}
    </td>
</tr>

<tr>
    <td>動画</td>
    <td>
        {% if post.video %}
            <video src="{{ post.video.url }}" controls></video>
        {% endif %}
    </td>
</tr>
            <tr><td>本文</td><td>{{create_post_form.content.value}}</td></tr>
            <tr><td>補足説明</td><td>{{create_post_form.description.value}}</td></tr>
        </table>
        {% for field in create_post_form %}
            {{field.as_hidden}}
        {% endfor %}
        <button type="submit" name="action" value="back">戻る</button>
        <button type="submit" name="action" value="done">登録</button>
    </form>    
{% endblock %}

tiptree_project/templates/posts/create_post.html
{% extends "base.html" %}
{% block content %}
<body>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {% for field in create_post_form %}
            <div>
                {{field.label}}
                {% if field.field.required %}
                    <span style="color: red;">*</span>
                {% endif %}
                {{ field }}
                {% if field.errors %}
                    {{ field.errors }}
                {% endif %}
            </div>
        {% endfor %}
    <input type="submit" value="確認"><br>
    </form>    
</body>
{% endblock %}

tiptree_project/templates/posts/edit_post.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<form method="POST" enctype="multipart/form-data">
{% csrf_token %}
{% for field in create_post_form %}
    <div>
        {{field.label}}
        {% if field.field.required %}
            <span style="color: red;">*</span>
        {% endif %}
        {{ field }}
        {% if field.errors %}
            {{ field.errors }}
        {% endif %}
    </div>
{% endfor %}
<input type="submit" value="更新する">
</form>
{% endblock %}

tiptree_project/templates/posts/helped_post_list.html
{% extends "base.html" %}
{% load static %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'posts/css/post_grid.css' %}">
<link rel="stylesheet" href="{% static 'posts/css/post_card.css' %}">
{% endblock %}

{% block content %}
<h2>役立った</h2>

  {% if page_obj %}
    <div class="post-grid">
      {% for post in page_obj %}
        {% include "components/post_card.html" %}
      {% endfor %}
    </div>
  {% endif %}

  {% include "components/pagination.html" %}

{% endblock %}

tiptree_project/templates/posts/post_detail.html
{% extends "base.html" %}
{% load static %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'posts/css/post_detail.css' %}">
{% endblock %}

{% block content %}

<div class="post-detail">

    <div class="maincontent">

        <div class="video-wrapper">
            <video controls src="{{ post.video.url }}"></video>
        </div>

        <div class="post-meta">
            <h1 class=post-title>{{ post.title }}</h1>
            <h3 class=post-category>{{ post.category }}</h3>
        </div>

        <div class="post-header">
            <div class="post-user">
                <img src="{{ post.user.profile_image.url }}" class="user-icon" alt="ユーザーアイコン">
                <span class="username">{{ post.user.username }}</span>

                {% if request.user == post.user %}

                    <a href="{% url 'posts:edit_post' post.id %}">編集</a>
                    <button  
                        class="open-delete-modal" 
                        data-url="{% url 'posts:post_delete' post.id %}"
                        data-text="この投稿を削除しますか？"
                        data-content="{{ post.title | truncatechars:30}}"
                    >
                        削除
                    </button>
                        
                {% endif %}
            </div>

            <div class="post-stats">
                <form action="{% url 'posts:toggle_help' post.id %}" method="post">
                    {% csrf_token %}
                    <button type="submit" class="help-btn">
                        {% if user in post.helped_users.all %}
                        <i class="fas fa-thumbs-up"></i>
                        {% else %}
                        <i class="far fa-thumbs-up"></i>
                        {% endif %}
                    </button>
                </form>

                <span class="comment_count">
                    <i class="far fa-comment-dots"></i>
                    <span>{{ post.comment_count }}</span>
                </span>
                <form action="{% url 'posts:toggle_save' post.id %}" method="post">
                    {% csrf_token %}
                    <button type="submit" class="save-btn">
                        {% if user in post.saved_users.all %}
                        <i class="fas fa-bookmark"></i>
                        {% else %}
                        <i class="far fa-bookmark"></i>
                        {% endif %}
                    </button>
                </form>
            </div>
        </div>

        <div class="post-body">
                <p id="post-text" class="collapsed">
                    {{ post.content|linebreaksbr }}
                </p>

                <button id="toggle-btn" class="toggle-btn">
                    もっと見る
                </button>
        </div>

        <div class="supplement">
           <div class="supplement_create">
                <h3>補足説明</h3>

                <form method="post" action="{% url 'posts:supplement_create' post.id %}" class="supplement-form">
                    {% csrf_token %}
                    {{ supplement_form.content }}
                    <button type="submit">補足を送信</button>
                </form>
           </div> 
        </div>
        <div class="supplement-list">
            {% for supplement in supplements %}
            <div class="supplement-item">
                <img src="{{ post.user.profile_image.url }}"
                    class="supplement-user-icon"
                    alt="ユーザーアイコン">

                <div class="supplement-content">
                    <div class="supplement-meta">
                        <span class="supplement-username">{{ post.user.username }}</span>
                        <small>{{ supplement.create_at }}</small>
                    </div>

                    <p class="supplement-text">
                        {{ supplement.content }}
                    </p>

                    <div class="supplement-actions">
                        <button class="reply-btn" data-id="{{ supplement.id }}">
                            返信
                        </button>

                        {% if request.user == supplement.user %}
                        <button  
                            class="open-delete-modal" 
                            data-url="{% url 'posts:supplement_delete' supplement.id %}"
                            data-text="この補足説明を削除しますか？"
                            data-content="{{ supplement.content | truncatechars:30 }}"
                        >
                            削除
                        </button>
                        {% endif %}
                    </div>

                    <form method="post" class="supplement-reply-form">
                        {% csrf_token %}
                        {{ supplement_reply_form.content }}
                        <button type="submit">送信</button>
                    </form>

                    <div class="supplement-replies">
                        {% for supplement_reply in supplement.supplement_replies.all %}
                        <div class="supplement-reply-item">
                            <img src="{{ supplement_reply.user.profile_image.url }}"
                                class="reply-user-icon"
                                alt="ユーザーアイコン">

                            <div class="reply-body">
                                <div class="reply-meta">
                                    <span class="reply-username">
                                        {{ supplement_reply.user.username }}
                                    </span>
                                    <small class="reply-date">
                                        {{ supplement_reply.create_at }}
                                    </small>
                                </div>
                            </div>
                            
                            <p class="supplement-reply-text">
                            {{ supplement_reply.content }}
                            </p>

                            {% if request.user == supplement_reply.user %}
                            <button 
                                class="open-delete-modal" 
                                data-url="{% url 'posts:supplement_reply_delete' supplement_reply.id %}"
                                data-text="この返信を削除しますか？"
                                data-content="{{ supplement_reply.content | truncatechars:30 }}"
                            >
                                削除
                            </button>
                            {% endif %}
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
            {% empty %}
                <p>まだ補足説明はありません</p>
            {% endfor %}
        </div>
        <div class="comment">
           <div class="comment_create">
                <h3>コメント</h3>

                <form method="post" action="{% url 'posts:comment_create' post.id %}" class="comment-form">
                    {% csrf_token %}
                    {{ comment_form.content }}
                    <button type="submit">送信</button>
                </form>
           </div> 
        </div>
        <div class="comment-list">
            {% for comment in comments %}
            <div class="comment-item">
                <img src="{{ post.user.profile_image.url }}"
                    class="comment-user-icon"
                    alt="ユーザーアイコン">

                <div class="comment-content">
                    <div class="comment-meta">
                        <span class="comment-username">{{ post.user.username }}</span>
                        <small>{{ comment.create_at }}</small>
                    </div>

                    <p class="comment-text">
                        {{ comment.content }}
                    </p>

                    <div class="comment-actions">
                        <button class="reply-btn" data-id="{{ comment.id }}">
                            返信
                        </button>

                        {% if request.user == comment.user %}
                        <button  
                            class="open-delete-modal" 
                            data-url="{% url 'posts:comment_delete' comment.id %}"
                            data-text="この補足説明を削除しますか？"
                            data-content="{{ comment.content | truncatechars:30 }}"
                        >
                            削除
                        </button>
                        {% endif %}
                    </div>

                    <form method="post" class="comment-reply-form">
                        {% csrf_token %}
                        {{ comment_reply_form.content }}
                        <button type="submit">送信</button>
                    </form>

                    <div class="comment-replies">
                        {% for comment_reply in comment.comment_replies.all %}
                        <div class="comment-reply-item">
                            <img src="{{ comment_reply.user.profile_image.url }}"
                                class="reply-user-icon"
                                alt="ユーザーアイコン">

                            <div class="reply-body">
                                <div class="reply-meta">
                                    <span class="reply-username">
                                        {{ comment_reply.user.username }}
                                    </span>
                                    <small class="reply-date">
                                        {{ comment_reply.create_at }}
                                    </small>
                                </div>
                            </div>
                            
                            <p class="comment-reply-text">
                            {{ comment_reply.content }}
                            </p>

                            {% if request.user == comment_reply.user %}
                            <button 
                                class="open-delete-modal" 
                                data-url="{% url 'posts:comment_reply_delete' comment_reply.id %}"
                                data-text="この返信を削除しますか？"
                                data-content="{{ comment_reply.content | truncatechars:30 }}"
                            >
                                削除
                            </button>
                            {% endif %}
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
            {% empty %}
                <p>まだコメントはありません</p>
            {% endfor %}
        </div>
    </div>

    <div class="side-content">

    </div>

</div>
<div id="delete-modal" class="modal hidden">
    <div class="modal-content">
        <button class="close-btn" type="button">×</button>

        <p class="modal-text">本当に削除しますか？</p>
        <p class="modal-subtext"></p>

        <form method="post" id="delete-form">
            {% csrf_token %}
            <button type="submit" class="confirm-delete">
                削除
            </button>
        </form>
    </div>
</div>
{% endblock %}

{% block extra_js %}
<script src="{% static 'posts/js/post_detail.js' %}"></script>
{% endblock %}