tiptree_project/home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('home', views.home, name = 'home'),
]

tiptree_project/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('create_post', views.create_post, name = 'create_post'),
    path('confirm', views.confirm, name = 'confirm'),
    path('edit_post/<int:post_id>', views.edit_post, name = 'edit_post'),
    path("<int:post_id>/save/", views.toggle_save, name="toggle_save"),
    path('saved', views.saved_post_list, name = 'saved_post_list'),
    path("<int:post_id>/help/", views.toggle_help, name="toggle_help"),
    path('helped', views.helped_post_list, name = 'helped_post_list'),
    path("<int:post_id>/", views.post_detail, name="post_detail"),
    path("<int:post_id>/comment/", views.comment_create, name="comment_create"),
    path("<int:post_id>/supplement/", views.supplement_create, name="supplement_create"),
    path("<int:post_id>/delete/", views.post_delete, name="post_delete"),
    path("supplement/<int:supplement_id>/supplement_reply/",views.supplement_reply,name="supplement_reply"),
    path("comment/<int:comment_id>/comment_reply/",views.comment_reply,name="comment_reply"),
    path("supplement/<int:supplement_id>/delete/",views.supplement_delete,name="supplement_delete"),
    path("supplement_reply/<int:supplement_reply_id>/delete/",views.supplement_reply_delete,name="supplement_reply_delete"),
    path("comment/<int:comment_id>/delete/",views.comment_delete,name="comment_delete"),
    path("comment_reply/<int:comment_reply_id>/delete/",views.comment_reply_delete,name="comment_reply_delete"),
]

tiptree_project/tiptree_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.portfolio, name='portfolio'),
    path('accounts/',include('accounts.urls')),
    path('home/',include('home.urls')),
    path('posts/',include(('posts.urls','posts'),namespace='posts')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

tiptree_project/templates/components/pagination.html
<div class="pagination">
  {% if page_obj.has_previous %}
    <a href="?page=1">&laquo;</a>
    <a href="?page={{ page_obj.previous_page_number }}">&lt;</a>
  {% endif %}

  {% for num in page_obj.paginator.page_range %}
    {% if num == page_obj.number %}
      <span class="current">[{{ num }}]</span>
    {% elif num >= page_obj.number|add:'-3' and num <= page_obj.number|add:'3' %}
      <a href="?page={{ num }}">{{ num }}</a>
    {% endif %}
  {% endfor %}

  {% if page_obj.has_next %}
    <a href="?page={{ page_obj.next_page_number }}">&gt;</a>
    <a href="?page={{ page_obj.paginator.num_pages }}">&raquo;</a>
  {% endif %}
</div>

tiptree_project/templates/components/post_card.html
<div class="postcard">
    <div class="post-user">
        <img src="{{ post.user.profile_image.url }}" class="user-icon" alt="ユーザーアイコン">
        <span class="username">{{ post.user.username }}</span>
    </div>

    <a href="{% url 'posts:post_detail' post.id %}" class="thumbnail-link">
        <img class="thumbnail" src="{{ post.thumbnail.url }}" alt="サムネイル">
    </a>

    <div class="post-info">
        <a href="{% url 'posts:post_detail' post.id %}" class="post-title-link">
            <h3>{{ post.title }}</h3>
        </a>
        <p class="post-category">{{ post.category }}</p>
    </div>

    <div class="post-stats">
        <span class="likes">
            <i class="far fa-thumbs-up"></i>
            <span>{{ post.help_count }}</span>
        </span>

        <span class="comments">
            <i class="far fa-comment-dots"></i>
            <span>{{ post.comment_count }}</span>
        </span>
        <form action="{% url 'posts:toggle_save' post.id %}" method="post">
            {% csrf_token %}
            <button type="submit" class="save-btn">
                {% if user in post.saved_users.all %}
                <i class="fas fa-bookmark"></i>
                {% else %}
                <i class="far fa-bookmark"></i>
                {% endif %}
            </button>
        </form>
    </div>
</div>