tiptree_project/accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from .views import CustomPasswordResetView,CustomPasswordResetDoneView,CustomPasswordResetConfirmView,CustomPasswordResetCompleteView

app_name = 'accounts'

urlpatterns = [
    path('regist', views.regist, name = 'regist'),
    path('confirm', views.confirm, name = 'confirm'),
    path('login', views.login_view, name = 'login'),
    path('logout', views.logout_view, name = 'logout'),
    path('password_reset', CustomPasswordResetView.as_view(), name='password_reset'), 
    path('password_reset/done', CustomPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', CustomPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', CustomPasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('my_page', views.my_page, name = 'my_page'),
    path('user_edit', views.user_edit, name = 'user_edit'),
    path('change_password', views.change_password, name = 'change_password'),
]

tiptree_project/home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('home', views.home, name = 'home'),
]

tiptree_project/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('create_post', views.create_post, name = 'create_post'),
    path('confirm', views.confirm, name = 'confirm'),
    path('edit_post/<int:post_id>', views.edit_post, name = 'edit_post'),
    path("<int:post_id>/save/", views.toggle_save, name="toggle_save"),
    path('saved', views.saved_post_list, name = 'saved_post_list'),
    path("<int:post_id>/help/", views.toggle_help, name="toggle_help"),
    path('helped', views.helped_post_list, name = 'helped_post_list'),
    path("<int:post_id>/", views.post_detail, name="post_detail"),
    path("<int:post_id>/comment/", views.comment_create, name="comment_create"),
    path("<int:post_id>/supplement/", views.supplement_create, name="supplement_create"),
    path("<int:post_id>/delete/", views.post_delete, name="post_delete"),
    path("supplement/<int:supplement_id>/supplement_reply/",views.supplement_reply,name="supplement_reply"),
    path("comment/<int:comment_id>/comment_reply/",views.comment_reply,name="comment_reply"),
    path("supplement/<int:supplement_id>/delete/",views.supplement_delete,name="supplement_delete"),
    path("supplement_reply/<int:supplement_reply_id>/delete/",views.supplement_reply_delete,name="supplement_reply_delete"),
    path("comment/<int:comment_id>/delete/",views.comment_delete,name="comment_delete"),
    path("comment_reply/<int:comment_reply_id>/delete/",views.comment_reply_delete,name="comment_reply_delete"),
]

tiptree_project/tiptree_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.portfolio, name='portfolio'),
    path('accounts/',include('accounts.urls')),
    path('home/',include('home.urls')),
    path('posts/',include(('posts.urls','posts'),namespace='posts')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

tiptree_project/accounts/models.py
from django.db import models
from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser, PermissionsMixin
)
from django.core.validators import FileExtensionValidator

class UserManager(BaseUserManager):
    
    def create_user(self, email, username, password, **extra_fields):
        if not email:
            raise ValueError('メールアドレスを入力してください')
        if not username:
            raise ValueError('アカウント名を入力してください')
        if not password:
            raise ValueError('パスワードを入力してください')
        email = self.normalize_email(email)
        user = self.model(email=email, username=username, **extra_fields)
        user.set_password(password)
        user.save()
        return user
    
    def create_superuser(self, email, username, password, **extra_fields):
        extra_fields['is_staff'] = True
        extra_fields['is_active'] = True
        extra_fields['is_superuser'] = True
        return self.create_user(email, username, password, **extra_fields)
        

class User(AbstractBaseUser, PermissionsMixin):
    
    username = models.CharField(max_length=20)
    email = models.EmailField(max_length=50,unique=True)
    profile_image = models.ImageField(
        upload_to='accounts/profile_images/',
        default='accounts/profile_images/default_profile.png',
        blank=True,null=True,
        validators=[FileExtensionValidator(['jpg','jpeg','png'],message="JPEGまたはPNG画像を選択してください")])
    bio = models.TextField(default='',blank=True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    uppdated_at = models.DateTimeField(auto_now=True)
    
    objects = UserManager()
    
    USERNAME_FIELD = 'email' #このテーブルのレコードを一意に識別するフィールド
    REQUIRED_FIELDS = ['username'] #createsuperuserの時に入力を求められる
    
    def __str__(self):
        return self.email
    
    class Meta:
        db_table ='user'

tiptree_project/accounts/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.core.validators import RegexValidator
from .models import User
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import PasswordResetForm
from django.contrib.auth.forms import SetPasswordForm
import re


User = get_user_model()

class RegistForm(forms.ModelForm):
    password1 = forms.CharField(label='パスワード', max_length=50, min_length=8, 
                               widget=forms.PasswordInput,error_messages={
                                   'invalid':'パスワードは半角英数字8字以上50字以下で入力してください',
                               },
                               validators=[
                                   RegexValidator(
                                       regex=r'^(?=.*[a-zA-Z])(?=.*[0-9])[a-zA-Z0-9]+$',
                                       message='パスワードは半角英数字両方含めてください'
                                   )])
    password2 = forms.CharField(label='パスワード再入力', max_length=50, min_length=8, 
                               widget=forms.PasswordInput,)
    
    class Meta:
        model = User
        fields = ('username','email')
        labels = {'username':'アカウント名', 'email':'メールアドレス'}
            
    def clean(self):
        cleaned_data = super().clean()
        password1 = cleaned_data.get('password1')
        password2 = cleaned_data.get('password2')
        if password1 != password2:
            raise ValidationError('パスワードが一致しません')
        
    def save(self, commit=False):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data.get('password1'))
        user.save()
        return user



class LoginForm(forms.Form):
    email = forms.EmailField(label="メールアドレス",
                             error_messages={
                                 'reqired' : 'メールアドレスを入力してください',
                                 'invalid' : '有効なメールアドレスを入力してください'
                             })
    password = forms.CharField(label="パスワード", max_length=50, min_length=8, 
                               widget=forms.PasswordInput,
                               error_messages={
                                   'required':'パスワードを入力してください',
                                   'invalid':'パスワードは半角英数字8字以上50字以下で入力してください',
                               },
                               validators=[
                                   RegexValidator(
                                       regex=r'^(?=.*[a-zA-Z])(?=.*[0-9])[a-zA-Z0-9]+$',
                                       message='パスワードは半角英数字両方含めてください'
                                   )
                               ])


class UserEditForm(forms.ModelForm):
    
    class Meta:
        model = User
        fields = ('profile_image','username','bio','email')
        labels = {'profile_image':'プロフィール画像',
                  'username':'アカウント名',
                  'bio':'自己紹介',
                  'email':'メールアドレス'
                  }
        required = {
            'profile_image':False, 'bio':False,
        }
        
        
class PasswordChangeForm(forms.ModelForm):
    old_password = forms.CharField(
        label='元のパスワード', widget = forms.PasswordInput
    )
    new_password1 = forms.CharField(label='新しいパスワード', max_length=50, min_length=8, 
                               widget=forms.PasswordInput,error_messages={
                                   'invalid':'パスワードは半角英数字8字以上50字以下で入力してください',
                               },
                               validators=[
                                   RegexValidator(
                                       regex=r'^(?=.*[a-zA-Z])(?=.*[0-9])[a-zA-Z0-9]+$',
                                       message='パスワードは半角英数字両方含めてください'
                                   )])
    new_password2 = forms.CharField(label='新しいパスワード(再入力)', max_length=50, min_length=8, 
                               widget=forms.PasswordInput,)
    
    class Meta:
        model = User
        fields = ()
        
    def clean(self):
        cleaned_data = super().clean()
        old_password = cleaned_data.get('old_password')
        new_password1 = cleaned_data.get('new_password1')
        new_password2 = cleaned_data.get('new_password2')
        if not self.instance.check_password(old_password):
            raise ValidationError('元のパスワードが違います')
        if new_password1 != new_password2:
            raise ValidationError('新しいパスワードが一致しません')
        
    def save(self, commit=False):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data.get('new_password1'))
        user.save()
        return user
    
    
class CustomPasswordResetForm(PasswordResetForm):
    email = forms.EmailField(
        label="メールアドレス",
        required=True,
        error_messages={
            'required':'メールアドレスを入力してください',
            'invalid':'正しいメールアドレスの形式で入力してください'
        }
    )
    
    
class CustomSetPasswordForm(SetPasswordForm):
    error_messages = {'password_mismatch':'パスワードが一致していません。'}
    
    new_password1 = forms.CharField(label='新しいパスワード', max_length=50, min_length=8, 
                               widget=forms.PasswordInput)
    new_password2 = forms.CharField(label='新しいパスワード(再入力)', max_length=50, min_length=8, 
                               widget=forms.PasswordInput,)
    
    def clean_new_password1(self):
        password = self.cleaned_data.get('new_password1')
        
        if not password:
            raise ValidationError('パスワードを入力してください。')
        
        if len(password) < 8 or len(password) > 50:
            raise ValidationError('パスワードは8字以上50字以下で入力してください。')
        
        if not re.match(r'^(?=.*[a-zA-Z])(?=.*[0-9])[a-zA-Z0-9]+$',password):
            raise ValidationError('パスワードは半角英数字両方含めてください')
        
        return password
    
    def clean(self):
        cleaned_data = super().clean()
        password1 = cleaned_data.get("new_password1")
        password2 = cleaned_data.get("new_password2")
        return cleaned_data
        

tiptree_project/accounts/views.py
from django.shortcuts import render, redirect
from . import forms
from posts.models import Post
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
import os
from django.core.files.storage import FileSystemStorage
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.views import PasswordResetView,PasswordResetConfirmView,PasswordResetCompleteView
from django.views import View
from .forms import CustomPasswordResetForm,CustomSetPasswordForm
from django.urls import reverse_lazy
from django.core.paginator import Paginator

def regist(request):
    regist_form = forms.RegistForm(request.POST or None)
    if regist_form.is_valid():
        password_mask = "●"* len(regist_form.cleaned_data['password1'])
        return render(request,'accounts/confirm.html',context={
            'regist_form':regist_form,
            'password_mask':password_mask
        })
    return render(request,"accounts/regist.html",context={
        'regist_form':regist_form
    })
 
    
def confirm(request):
    if request.method == "POST":
        regist_form = forms.RegistForm(request.POST)
        action = request.POST.get('action')
        
        if action == 'back':
            return render(request,"accounts/regist.html",context={
                'regist_form':regist_form
            })
            
        elif action == 'done' and regist_form.is_valid():
            user = regist_form.save()
            login(request, user)
            return redirect('home:home')
     
        if regist_form.is_valid():
            password_mask = "●"* len(regist_form.cleaned_data['password1'])
            
        return render(request,"accounts/confirm.html",context={
            'regist_form':regist_form,
            'password_mask':password_mask
        })
    
    return redirect('accounts:regist')


def login_view(request):
    login_form = forms.LoginForm(request.POST or None)
    if login_form.is_valid():
        email = login_form.cleaned_data['email']
        password = login_form.cleaned_data['password']
        user = authenticate(email=email, password=password)
        if user:
            login(request, user)
            return redirect('home:home')
        else:
            messages.warning(request,'メールアドレスまたはパスワードが正しくありません')
    return render(
        request, 'accounts/login.html', context={
            'login_form':login_form,
        }
    )


@login_required
def logout_view(request):
    logout(request)
    return redirect('home:home')

@login_required
def my_page(request):
    post_list = Post.objects.filter(
        user=request.user
    ).order_by('-created_at')

    paginator = Paginator(post_list, 12)  # 1ページ12件
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    return render(request, 'accounts/my_page.html', context = {
        'page_obj': page_obj,
    })
    

@login_required
def user_edit(request):
    user_edit_form = forms.UserEditForm(
        request.POST or None, request.FILES or None, instance=request.user
    )
    if user_edit_form.is_valid():
        user_edit_form.save()
        return redirect('accounts:my_page')
    
    return render(request,'accounts/user_edit.html',context={
        'user_edit_form':user_edit_form
    })


@login_required
def change_password(request):
    password_change_form = forms.PasswordChangeForm(
        request.POST or None, instance=request.user
    )
    if password_change_form.is_valid():
        user = password_change_form.save(commit=True)
        update_session_auth_hash(request, user)
        return redirect('accounts:my_page')
    return render(request,'accounts/change_password.html',context={
        'password_change_form':password_change_form
    })


class CustomPasswordResetView(PasswordResetView):
    form_class = CustomPasswordResetForm
    template_name = "accounts/password_reset_form.html"
    success_url = reverse_lazy('accounts:password_reset_done')
    email_template_name = "accounts/password_reset_email.html"
    
    def form_valid(self, form):
        self.request.session['reset_email'] = form.cleaned_data['email']
        return super().form_valid(form)
    
class CustomPasswordResetDoneView(View):
    template_name = "accounts/password_reset_done.html"
    
    def get(self, request):
        email = request.session.get('reset_email','')
        return render(request,self.template_name,context={
            'email':email
        })
        
class CustomPasswordResetConfirmView(PasswordResetConfirmView):
    template_name = "accounts/password_reset_confirm.html"
    success_url = reverse_lazy('accounts:password_reset_complete')
    form_class = CustomSetPasswordForm
    
class CustomPasswordResetCompleteView(PasswordResetCompleteView):
    template_name = "accounts/password_reset_complete.html"

tiptree_project/templates/accounts/change_password.html
{% extends "base.html" %}
{% block content %}
<h1>パスワード変更</h1>
<form method="POST">
{% csrf_token %}
{{ password_change_form }}
<input type="submit" value="保存">
</form>
{% endblock %}

tiptree_project/templates/accounts/confirm.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <title>confirm</title>
</head>
<body>
    <form method="POST" action="{% url 'accounts:confirm'%}">
        {% csrf_token %}
        <h1>新規アカウント登録 確認</h1>
        <h2>登録内容をご確認ください</h2>
        <table>
            <tr><td>アカウント名</td><td>{{regist_form.username.value}}</td></tr>
            <tr><td>メールアドレス</td><td>{{regist_form.email.value}}</td></tr>
            <tr><td>パスワード</td><td><pre>{{ password_mask }}</pre></td></tr>
        </table>
        {% for field in regist_form %}
            {{field.as_hidden}}
        {% endfor %}
        <button type="submit" name="action" value="back">戻る</button>
        <button type="submit" name="action" value="done">登録</button>
    </form>    
</body>
</html>

tiptree_project/templates/accounts/login.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <title>login</title>
</head>
<body>
    <form method="POST">
        {% csrf_token %}
        <h1>Tip Tree</h1>
        <h2>アカウントログイン</h2>
        {% if messages %}
            {% for message in messages %}
                <p>{{ message }}<p>
            {% endfor %}
        {% endif %}
        {{ login_form }}
        <input type="submit" value="ログイン"><br>
        <a href ="{% url 'accounts:regist' %}">アカウント登録</a><br>
        <a href ="{% url 'accounts:password_reset' %}">パスワードをお忘れですか？</a>
    </form>    
</body>
</html>

tiptree_project/templates/accounts/my_page.html
{% extends "base.html" %}
{% load static %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'posts/css/post_grid.css' %}">
<link rel="stylesheet" href="{% static 'posts/css/post_card.css' %}">
{% endblock %}
{% block content %}
<img src="{{ user.profile_image.url }}"></br>
<table>
    <tr><td>アカウント名:</td><td>{{user.username}}</td></tr>
    <tr><td>自己紹介:</td><td>{{user.bio}}</td></tr>
</table>

<span>マイアクション</span>
<div class="my-action">
  <span>
    <a href="{% url 'posts:saved_post_list' %}"><i class="fas fa-bookmark"></i>あとで見る</a>
  </span>
  <span>
    <a href="{% url 'posts:helped_post_list' %}"><i class="far fa-thumbs-up"></i>役立った</a>
  </span>
</div>

<a href="{% url 'accounts:user_edit' %}">
    <button type="button">編集</button>
</a>
<form action="{% url 'accounts:logout' %}" method="post">
    {% csrf_token %}
    <input type="submit" value="ログアウト">
</form>
<a href ="{% url 'accounts:change_password' %}">パスワード変更</a>
<div class="post-grid">
  {% for post in page_obj %}
    {% include "components/post_card.html" %}
  {% endfor %}
</div>
<div class="pagination">
  {% if page_obj.has_previous %}
    <a href="?page=1">&laquo;</a>
    <a href="?page={{ page_obj.previous_page_number }}">&lt;</a>
  {% endif %}

  {% for num in page_obj.paginator.page_range %}
    {% if num == page_obj.number %}
      <span class="current">[{{ num }}]</span>
    {% elif num >= page_obj.number|add:'-3' and num <= page_obj.number|add:'3' %}
      <a href="?page={{ num }}">{{ num }}</a>
    {% endif %}
  {% endfor %}

  {% if page_obj.has_next %}
    <a href="?page={{ page_obj.next_page_number }}">&gt;</a>
    <a href="?page={{ page_obj.paginator.num_pages }}">&raquo;</a>
  {% endif %}
</div>
{% endblock %}

tiptree_project/templates/accounts/password_reset_complete.html
<h1>＜パスワード再設定＞</h1>
<p>再設定が完了しました。</p>
<form action="{% url 'accounts:login' %}">
    <button type="submit">ログイン画面へ</button>
</form>

tiptree_project/templates/accounts/password_reset_confirm.html
{% if form %}
    <h1>TipTree</h1>
    <h2>＜パスワード再設定＞</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.errors }}
        <div>
            {{ form.new_password1.label_tag }}
            {{ form.new_password1 }}
            <small>半角英数字を組み合わせて8字以上50字以内で入力してください</small>
        </div>
        <div>
            {{ form.new_password2.label_tag }}
            {{ form.new_password2 }}
        </div>
        <input type="submit" value="登録">
    </form>
{% else %}
    <h1>パスワードリセットエラー</h1>
    <p>次のエラーが発生しました。</p>
    <p>パスワードリセットリンクが無効です。</br>再度お試しください</p>
    <a href="{% url 'accounts:password_reset' %}"> パスワード再設定ページへ</a>
{% endif %}

tiptree_project/templates/accounts/password_reset_done.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <title>password_reset_done</title>
</head>
<body>
    <h1>TipTree</h1>
    <h2>＜パスワード再設定のご案内＞</h2>
    <h3>以下のメールアドレスにパスワード再設定用のURLをお送りしました。</h3></br>
    <h3>メールのご確認をお願いいたします。</h3></br>
    {{ email }}
    <h4>・メールの受信までに数分かかる場合があります</h4></br>
    <h4>・Gmailをご利用の方は、迷惑メールフォルダや「プロモーション」タブもご確認ください。</h4></br>
    <h4>・メールが届かない場合は、しばらく待ってから再度お試しください。</h4></br>
    <a href="{% url 'accounts:login' %}"> ログイン画面</a>

tiptree_project/templates/accounts/password_reset_email.html
<p>こんにちは。TipTreeです。</p>

<p>パスワードの再設定をご希望とのことで、このメールをお送りしています。</br>
以下のURLをクリックして、新しいパスワードを設定してください。</p>

<p>▼パスワード再設定リンク（1時間以内に有効）</p>
<p><a href="{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}"></a></p>

<p>この操作に心当たりがない場合は、このメールを破棄してください。</p>

<p>----------------------------------------------------------</p>
<p>「TipTree」</p>
<p>このメールアドレスは送信専用です。</p>

tiptree_project/templates/accounts/password_reset_form.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <title>password_reset</title>
</head>
<body>
    <h1>TipTree</h1>
    <h2>＜パスワード再設定のご案内＞</h2>
    <h3>ご登録いただいたメールアドレスにパスワード再設定のご案内を送信いたします。</h3></br>
    <h3>ご登録いただいたメールアドレスを入力し「送信」ボタンを押してください。</h3></br>

<form method="post">
    {% csrf_token %}
    <div>
        <label for="id_email" class="form-label">メールアドレス</label>
        {{ form.email }}
        {% if form.email.errors %}
        <div class="text-danger small">
            {{ form.email.errors }}
        </div>
        {% endif %}
    </div>
    <div>
        <input type="submit" value="送信"><br>
        <a href="{% url 'accounts:login' %}"> ログイン画面に戻る</a>
    </div>
</form>
</body>

tiptree_project/templates/accounts/regist.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <title>regist</title>
</head>
<body>
    <form method="POST">
        {% csrf_token %}
        <h1>新規アカウント登録</h1>
        <div>
            {{ regist_form.username.label_tag }}
            {{ regist_form.username }}
        </div>
        <div>
            {{ regist_form.email.label_tag }}
            {{ regist_form.email }}
        </div>
        <div>
            {{ regist_form.password1.label_tag }}
            {{ regist_form.password1 }}
            <small>半角英数字を組み合わせて8字以上50字以内で入力してください</small>
        </div>
        <div>
            {{ regist_form.password2.label_tag }}
            {{ regist_form.password2 }}
        </div>
    <input type="submit" value="確認"><br>
    <a href ="{% url 'accounts:login' %}">ログイン画面に戻る</a>
    </form>    
</body>
</html>

tiptree_project/templates/accounts/user_edit.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<form method="POST" enctype="multipart/form-data">
{% csrf_token %}
<div class="image-preview">
    <img id="preview-image" src="{{ user.profile_image.url }}" alt="現在のプロフィール画像">    
</div>
<input type="file" name="profile_image" id="id_image" accept="image/*">
<div>
    {{ user_edit_form.username.label_tag }}
    {{ user_edit_form.username }}
</div>
<div>
    {{ user_edit_form.bio.label_tag }}
    {{ user_edit_form.bio }}
</div>
<div>
    {{ user_edit_form.email.label_tag }}
    {{ user_edit_form.email }}
</div>
<input type="submit" value="保存">
</form>
<a href="{% url 'accounts:change_password' %}">パスワード変更</a>
{% endblock %}
{% block extra_js %}
<script src="{% static 'accounts/js/user_edit.js' %}"></script>
{% endblock %}